services:
  app:
    image: node:latest
    command: >
      bash -c "
        cp -rf /host/package.json /host/packages /commons/ &&
        yarn set version berry &&
        yarn install &&
        yarn dev
      "
    ports:
      - 5000:3000
    working_dir: /commons/examples/sandbox
    volumes:
      - commons:/commons
      - ../..:/host:ro
      - .:/commons/examples/sandbox

    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: app

  mongo:
    image: mongo:latest
    volumes:
      - data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: app

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/

volumes:
  data:
  commons:
